{
 "title": "Build metrics",
 "time": { "from": "2023-10-06T09:35:35.514Z", "to": "2023-10-17T07:22:13.173Z" },
 "panels": [
  {
   "title": "Recent Runs",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT ROW_NUMBER() OVER (ORDER BY id) AS \"#\", id AS \"ID\", branch AS \"Branch\", created_at AS \"Created At\", status AS \"Status\", is_approval AS \"Approved\" FROM insights LIMIT 50 "
    }
   ]
  },
  {
   "title": "Lead Time (Hours)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT ROW_NUMBER() OVER (ORDER BY id) AS \"Row Number\", ((EXTRACT(EPOCH FROM (stopped_at - created_at))) / 3600) as \"Lead Time (hours)\"\r\nFROM insights\r\nORDER BY id;\r\n"
    }
   ]
  },
  {
   "title": "Time Between Runs",
   "type": "timeseries",
   "description": "Time between the current run and the previous run",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT \"Created At\", \r\n       EXTRACT(EPOCH FROM \"Interval Between Runs\")/3600 AS \"Interval Between Runs (Hours)\"\r\nFROM (\r\n  SELECT created_at AS \"Created At\",\r\n  created_at - LAG(created_at) OVER (ORDER BY created_at) AS \"Interval Between Runs\",\r\n  ROW_NUMBER() OVER (ORDER BY created_at) AS rn\r\n  FROM insights\r\n) t\r\nWHERE rn > 1;\r\n"
    }
   ]
  },
  {
   "title": "Run Durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT created_at, duration AS \"Duration (Seconds)\" FROM insights LIMIT 50 "
    }
   ]
  },
  {
   "title": "Security Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT id AS \"ID\",\r\ncontext AS \"Context\",\r\nseverity AS \"Severity\",\r\nsecurity_severity AS \"Security Severity\",\r\ncreated_at AS \"Created At\",\r\nhtml_url AS \"URL\",\r\nstate AS \"State\",\r\nfixed_by AS \"Fixed By\",\r\ndismissed_by AS \"Dismissed By\",\r\ndismissed_at AS \"Dismissed At\",\r\ndismissed_reason AS \"Dismissed Reason\"\r\nFROM alerts LIMIT 50 "
    }
   ]
  },
  {
   "title": "Security Severity",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT security_severity, COUNT(*)\r\nFROM alerts\r\nGROUP BY security_severity;"
    }
   ]
  },
  {
   "title": "Warnings Severity",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT severity, COUNT(*)\r\nFROM alerts\r\nGROUP BY severity;"
    }
   ]
  },
  {
   "title": "Builds Per Week",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    COUNT(created_at)\r\nFROM \r\n    insights \r\nWHERE\r\n    created_at >= NOW() - INTERVAL '7 days'\r\n"
    }
   ]
  },
  {
   "title": "Tests Pass Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    1 - ((SELECT COUNT(*) FROM insights WHERE status = 'failed')::decimal /\r\n    (SELECT COUNT(*) FROM insights)) AS \"Pass Rate\"\r\n"
    }
   ]
  },
  {
   "title": "Estimated Average Time Between Runs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT start_time, avg_time_between AS \"Hours\" FROM avg_time_between_runs LIMIT 50 "
    }
   ]
  },
  {
   "title": "Estimated Run Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT start_time, avg_duration as \"Seconds\" FROM avg_durations LIMIT 50 "
    }
   ]
  }
 ]
}