{
 "title": "Build metrics",
 "time": { "from": "2023-10-06T09:27:47.644Z", "to": "2023-10-16T06:21:22.469Z" },
 "panels": [
  {
   "title": "Run Durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT created_at, duration AS \"Duration\" FROM insights LIMIT 50 "
    }
   ]
  },
  {
   "title": "Time Between Runs",
   "type": "timeseries",
   "description": "Time between the current run and the previous run",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"Created At\", \r\n       EXTRACT(EPOCH FROM \"Interval Between Runs\")/3600 AS \"Interval Between Runs in Hours\"\r\nFROM (\r\n  SELECT created_at AS \"Created At\",\r\n  created_at - LAG(created_at) OVER (ORDER BY created_at) AS \"Interval Between Runs\",\r\n  ROW_NUMBER() OVER (ORDER BY created_at) AS rn\r\n  FROM insights\r\n) t\r\nWHERE rn > 1;\r\n"
    }
   ]
  },
  {
   "title": "Recent Runs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT * FROM insights LIMIT 50 "
    }
   ]
  },
  {
   "title": "Security Alerts",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT id AS \"ID\",\r\ncreated_at AS \"Created At\",\r\nhtml_url AS \"URL\",\r\nstate AS \"State\",\r\nfixed_by AS \"Fixed By\",\r\ndismissed_by AS \"Dismissed By\",\r\ndismissed_at AS \"Dismissed At\",\r\ndismissed_reason AS \"Dismissed Reason\"\r\nFROM alerts LIMIT 50 "
    }
   ]
  },
  {
   "title": "Builds Within 14 Days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    COUNT(created_at)\r\nFROM \r\n    insights \r\nWHERE\r\n    created_at >= NOW() - INTERVAL '14 days'\r\n"
    }
   ]
  }
 ]
}