version: '3.9'
services:
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=passw0rd
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    networks:
      - sonarqube_network
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=sonar
    networks:
      - sonarqube_network
networks:
  sonarqube_network:
